var albums = [
    {
        "title": "True",
        "artist": "Avicii",
        "img": "true",
        "fav": "Wake Me Up (feat. Aloe Blacc)",
        "link": "",
    },
    {
        "title": "1000 gecs",
        "artist": "100 gecs",
        "img": "1kgecs",
        "fav": "gecgecgec",
        "link": "",
    },
    {
        "title": "10,000 gecs",
        "artist": "100 gecs",
        "img": "10kgecs",
        "fav": "Frog On The Floor",
        "link": "",
    },
    {
        "title": "True (Avicii by Avicii)",
        "artist": "Avicii",
        "img": "trueaba",
        "fav": "Dear Boy (Avicii by Avicii)",
        "link": "",
    },
    {
        "title": "Stories",
        "artist": "Avicii",
        "img": "stories",
        "fav": "Sunset Jesus",
        "link": "",
    },
    {
        "title": "AVĪCI (01)",
        "artist": "Avicii",
        "img": "avici01",
        "fav": "Friend Of Mine (feat. Vargas & Lagola)",
        "link": "",
    },
    {
        "title": "Tim",
        "artist": "Avicii",
        "img": "tim",
        "fav": "SOS (feat. Aloe Blacc)",
        "link": "",
    },
    {
        "title": "Breathing",
        "artist": "Ben Böhmer",
        "img": "breathing",
        "fav": "Wall Of Strings",
        "link": "",
    },
    {
        "title": "create together vol. 3",
        "artist": "bitbird / various artists",
        "img": "createtogether3",
        "fav": "Unseen Skies (2045, a r u k a., fungeey)",
        "link": "",
    },
    {
        "title": "punk2",
        "artist": "brakence",
        "img": "punk2",
        "fav": "dropout",
        "link": "",
    },
    {
        "title": "hypochondriac",
        "artist": "brakence",
        "img": "hypochondriac",
        "fav": "5g",
        "link": "",
    },
    {
        "title": "BRONSON",
        "artist": "BRONSON",
        "img": "bronson",
        "fav": "CONTACT",
        "link": "",
    },
    {
        "title": "NOT TiGHT",
        "artist": "DOMi & JD BECK",
        "img": "nottight",
        "fav": "DUKE",
        "link": "",
    },
    {
        "title": "Rising",
        "artist": "Duskus",
        "img": "rising",
        "fav": "No I'm Not, Yes I Am",
        "link": "",
    },
    {
        "title": "Healers Vol. 1",
        "artist": "Duskus",
        "img": "healers1",
        "fav": "Hope",
        "link": "",
    },
    {
        "title": "Gravity",
        "artist": "Gryffin",
        "img": "gravity",
        "fav": "Need Your Love (& Seven Lions with Noah Kahan)",
        "link": "",
    },
    {
        "title": "Ashes",
        "artist": "ILLENIUM",
        "img": "ashes",
        "fav": "With You (& Quinn XCII)",
        "link": "",
    },
    {
        "title": "Awake",
        "artist": "ILLENIUM",
        "img": "awake",
        "fav": "Beautiful Creatures (& MAX)",
        "link": "",
    },
    {
        "title": "ASCEND",
        "artist": "ILLENIUM",
        "img": "ascend",
        "fav": "Hold On (with Georgia Ku)",
        "link": "",
    },
    {
        "title": "Fallen Embers",
        "artist": "ILLENIUM",
        "img": "fallenembers",
        "fav": "Blame Myself (& Tori Kelly)",
        "link": "",
    },
    {
        "title": "ILLENIUM",
        "artist": "ILLENIUM",
        "img": "illenium",
        "fav": "Drwn",
        "link": "",
    },
    {
        "title": "Frailty",
        "artist": "Jane Remover",
        "img": "frailty",
        "fav": "your clothes",
        "link": "",
    },
    {
        "title": "Census Designated",
        "artist": "Jane Remover",
        "img": "censusdesignated",
        "fav": "Video",
        "link": "",
    },
    {
        "title": "it's hard to see color [When You're So Impossibly Far Away*]",
        "artist": "Jaron",
        "img": "ihtsc",
        "fav": "WIRES222",
        "link": "",
    },
    {
        "title": "1000 Faces",
        "artist": "Jason Ross",
        "img": "1000faces",
        "fav": "Chains",
        "link": "",
    },
    {
        "title": "Places We Don't Know",
        "artist": "Kasbo",
        "img": "placeswedk",
        "fav": "Aldrig Mer (& TENDER)",
        "link": "",
    },
    {
        "title": "The Making of a Paracosm",
        "artist": "Kasbo",
        "img": "paracosm",
        "fav": "Talk Slow (& Noomi)",
        "link": "",
    },
    {
        "title": "Kaskade Christmas Deluxe",
        "artist": "Kaskade",
        "img": "kaskadechristmas",
        "fav": "God Rest Ye (feat. Debra Fotheringham)",
        "link": "",
    },
    {
        "title": "Good Faith",
        "artist": "Madeon",
        "img": "goodfaith",
        "fav": "Miracle",
        "link": "",
    },
    {
        "title": "Nurture",
        "artist": "Porter Robinson",
        "img": "nurture",
        "fav": "Mirror",
        "link": "",
    },
    {
        "title": "Wide-Eyed",
        "artist": "Said The Sky",
        "img": "wideeyed",
        "fav": "Superstar (& Dabin, Linn)",
        "link": "",
    },
    {
        "title": "Sentiment",
        "artist": "Said The Sky",
        "img": "sentiment",
        "fav": "Spider (& Boy In Space)",
        "link": "",
    },
    {
        "title": "Harpsinger",
        "artist": "Sakuraburst",
        "img": "harpsinger",
        "fav": "Roof of the World (& Case Closed)",
        "link": "",
    },
    {
        "title": "album1",
        "artist": "San Holo",
        "img": "album1",
        "fav": "lift me from the ground (& Sofie Winterson)",
        "link": "",
    },
    {
        "title": "stay vibrant",
        "artist": "San Holo",
        "img": "stayvibrant",
        "fav": "idk anything (demo)",
        "link": "",
    },
    {
        "title": "bb u ok?",
        "artist": "San Holo",
        "img": "bbuok",
        "fav": "you've changed, i've changed (& Chet Porter)",
        "link": "",
    },
    {
        "title": "EXISTENTIAL DANCE MUSIC",
        "artist": "San Holo",
        "img": "edm",
        "fav": "SILENCE IN MY MIND (feat. Sofie Winterson)",
        "link": "",
    },
    {
        "title": "Illusion of Perfection",
        "artist": "Spencer Brown",
        "img": "illusion",
        "fav": "Audio (& Liam Hathaway)",
        "link": "",
    },
    {
        "title": "skin purifying treatment",
        "artist": "underscores",
        "img": "skinpt",
        "fav": "regulate you",
        "link": "",
    },
    {
        "title": "fishmonger",
        "artist": "underscores",
        "img": "fishmonger",
        "fav": "Kinko's field trip 2006",
        "link": "",
    },
    {
        "title": "boneyard aka fearmonger",
        "artist": "underscores",
        "img": "fearmonger",
        "fav": "Girls and boys, stay out of the #@$%ing lake!",
        "link": "",
    },
    {
        "title": "Wallsocket",
        "artist": "underscores",
        "img": "wallsocket",
        "fav": "Uncanny long arms (with Jane Remover)",
        "link": "",
    },
    {
        "title": "Virtual Self",
        "artist": "Virtual Self",
        "img": "virtualself",
        "fav": "Particle Arts",
        "link": "",
    },
    {
        "title": "nintendo 64",
        "artist": "wes mills",
        "img": "n64",
        "fav": "finish line",
        "link": "",
    },
    {
        "title": "Pages",
        "artist": "William Black",
        "img": "pages",
        "fav": "Ruins (& Micah Martin)",
        "link": "",
    },
    {
        "title": "The Nature of Hope",
        "artist": "William Black",
        "img": "naturehope",
        "fav": "Want It All (& Sofia Quinn)",
        "link": "",
    },
];