var albums = [
    {
        "title": "True",
        "artist": "Avicii",
        "released": "2013-09-13",
        "img": "true",
        "content": "This album gets a special place at the top of this page.",
        "fav": "",
    },
    {
        "title": "10,000 gecs",
        "artist": "100 gecs",
        "released": "2023-03-17",
        "img": "10kgecs",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "AVĪCI (01)",
        "artist": "Avicii",
        "released": "2017-08-10",
        "img": "avici01",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "create together vol. 3",
        "artist": "bitbird / various artists",
        "released": "2022-06-01",
        "img": "createtogether3",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "hypochondriac",
        "artist": "brakence",
        "released": "2022-12-02",
        "img": "hypochondriac",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "NOT TiGHT",
        "artist": "DOMi & JD BECK",
        "released": "2022-06-29",
        "img": "nottight",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Awake",
        "artist": "ILLENIUM",
        "released": "2017-09-21",
        "img": "awake",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "ASCEND",
        "artist": "ILLENIUM",
        "released": "2019-08-16",
        "img": "ascend",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Frailty",
        "artist": "Jane Remover",
        "released": "2021-11-12",
        "img": "frailty",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Census Designated",
        "artist": "Jane Remover",
        "released": "2023-10-20",
        "img": "censusdesignated",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "it's hard to see color [When You're So Impossibly Far Away*]",
        "artist": "Jaron",
        "released": "2022-02-22",
        "img": "ihtsc",
        "content": "Sample Text",
        "fav": "WIRES222",
    },
    {
        "title": "The Making of a Paracosm",
        "artist": "Kasbo",
        "released": "2020-10-23",
        "img": "paracosm",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Good Faith",
        "artist": "Madeon",
        "released": "2019-11-15",
        "img": "goodfaith",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Nurture",
        "artist": "Porter Robinson",
        "released": "2023-04-23",
        "img": "nurture",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Wide-Eyed",
        "artist": "Said The Sky",
        "released": "2018-07-20",
        "img": "wideeyed",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Sentiment",
        "artist": "Said The Sky",
        "released": "2022-02-18",
        "img": "sentiment",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "album1",
        "artist": "San Holo",
        "released": "2018-09-21",
        "img": "album1",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "stay vibrant",
        "artist": "San Holo",
        "released": "2020-03-27",
        "img": "stayvibrant",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "bb u ok?",
        "artist": "San Holo",
        "released": "2021-06-04",
        "img": "bbuok",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Illusion of Perfection",
        "artist": "Spencer Brown",
        "released": "2018-05-11",
        "img": "illusion",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Where U Are",
        "artist": "Throttle",
        "released": "2019-10-11",
        "img": "whereuare",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "fishmonger",
        "artist": "underscores",
        "released": "2021-03-25",
        "img": "fishmonger",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Wallsocket",
        "artist": "underscores",
        "released": "2023-09-22",
        "img": "wallsocket",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "Virtual Self",
        "artist": "Virtual Self",
        "released": "2017-11-29",
        "img": "virtualself",
        "content": "Sample Text",
        "fav": "",
    },
    {
        "title": "nintendo 64",
        "artist": "wes mills",
        "released": "2023-04-26",
        "img": "n64",
        "content": "wes mills tried to create a nostalgic-sounding EP with <strong>nintendo 64</strong>, and even though I had not even been alive during the reign of the N64, wes mills' nostalgia is tangible through this 4-track release. Big recommendation.\n<a href='https://youtu.be/XK27UYX4zs0'>The</a> <a href='https://youtu.be/TGQR0yoyx4I'>music</a> <a href='https://youtu.be/SxOxL5mASgY'>videos</a> are absolutely worth a watch as well; their playful and amateurish vibe (which I earnestly mean in the best way possible!!) really evokes the feeling of being a child and immersing yourself in your favourite activities. This 10-minute EP is truly a breath of fresh air.",
        "fav": "finish line",
    },
];